language: c

matrix:
    include:
        - env: test="x64 4.8.4 (make)"
          os: linux
          dist: trusty
          compiler: gcc
          script: make

        - env: test="x64 4.8.4 (autotools)"
          os: linux
          dist: trusty
          compiler: gcc
          script: ./autogen.sh && ./configure && make distcheck

        - env: test="x64 5.0 (autotools)"
          os: linux
          dist: trusty
          compiler: clang
          script: ./autogen.sh && ./configure && make distcheck

        - env: test="x64 4.8.4 (CMake gcc)"
          os: linux
          dist: trusty
          compiler: gcc
          before_script:
              - mkdir gcc_rel && cd gcc_rel
              - cmake ..
          script:  make

        - env: test="x64 5.0 (CMake clang)"
          os: linux
          dist: trusty
          compiler: clang
          before_script:
              - mkdir clang_rel && cd clang_rel
              - cmake ..
          script:  make

        - env: test="x64 5.0 (CMake clang - Ninja) Debug"
          os: linux
          dist: trusty
          compiler: clang
          before_script:
              - mkdir clang_ninja_dbg && cd clang_ninja_dbg
              - cmake .. -GNinja -DCMAKE_BUILT_TYPE=Debug
          script:  ninja

        - env: test="x64 5.0 (CMake Android-15 armeabi-v7a)"
          language: android
          install: 
              - echo y | sdkmanager "ndk-bundle"
              - echo y | sdkmanager "cmake;3.6.4111459"
          before_script:
              - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
              - export ANDROID_CMAKE=$ANDROID_HOME/cmake/3.6.4111459/bin/cmake
              - mkdir android15_armeabiv7a_rel && cd android15_armeabiv7a_rel
              - cmake --version
              - $ANDROID_CMAKE --version
              - $ANDROID_CMAKE -DANDROID_PLATFORM=android-15 -DANDROID_ABI=armeabi-v7a -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake ..
          script:  make

addons:
    apt:
        packages:
            - autoconf
            - automake
            - libtool
            - m4
            - cmake
            - ninja-build
        sources:
            - ubuntu-toolchain-r-test
